### ISSUE TITLE
Single pod and HorizontalPodAutoscaler Example

### ISSUE THREAD

**Issue by hadminh** [typesense/typesense-kubernetes#3]
Thanks for an awesome software and [example](https://github.com/typesense/typesense-kubernetes/blob/master/base/install.yaml). 

This is more of a help request. 

I am a startup company, and High Availability is too expensive for me, as I am dealing with a large dataset. I have about 3.2 million records similar to your airbnb example. Note that I am also self-hosting the map tiles server on the same node IoI

The example [here](https://github.com/typesense/typesense-kubernetes/blob/master/base/install.yaml) requires to manually modify the ConfigMap and increment 
`typesense-{increment}.ts.typesense.svc.cluster.local:8107:8108` 
based on how many replicaset I have. 

To be honest I am using Kubernetes only for its autoscaling capabilities.
(I mean Kubernetes without autoscaling capability doesn't worth the effort :) )

Is it possible to make a single Statefulset pod of a Typesense and horizontally auto scale it? Can it choose the typesense-0 as a master and the rest for read access, without any configuration?

**Comment by Bug-Reaper** [comment]
+1 for more examples on auto-scale config.

**Comment by mojtabacazi** [comment]
+1

**Comment by sagungargs15** [comment]
+1 can you help with a helm chart example for installation or something beyond what is offered in the above

**Comment by hadminh** [comment]
Not sure if you were asking me but the YouTube link I posted below is the best resource to learn about Statefulsets. 

https://www.youtube.com/watch?v=eUa-IDPGL-Q

The Typesense helm chart basically creates a highly available or HA Statefulset of Typesense pods. 
In the video, the instructor talks about mongo-db master/slave or leader/follower relationship. The very concept can be applied to Typesense. 
This config map from the helm chart defines that relationship.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeslist
  namespace: typesense
data:
  nodes: "typesense-0.ts.typesense.svc.cluster.local:8107:8108,typesense-1.ts.typesense.svc.cluster.local:8107:8108,typesense-2.ts.typesense.svc.cluster.local:8107:8108" 

```
